# Generated by Django 6.0.5 on 2026-05-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('college_year', models.CharField(blank=True, max_length=20)),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('target_role', models.CharField(blank=True, max_length=50)),
                ('weak_area', models.CharField(blank=True, max_length=100)),
                ('daily_study_hours', models.IntegerField(default=0)),
            ],
        ),
    ]
