# Generated by Django 6.0.5 on 2026-05-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='college_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='daily_study_hours',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_level',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
