# Generated by Django 6.0.5 on 2026-05-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_branch_remove_profile_college_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weak_area',
        ),
    ]
