# Generated by Django 6.0.5 on 2026-05-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='Weekly Goals', max_length=50),
        ),
    ]
